<?php

namespace eventBundle\Repository;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercher($titre)
    {
        $sql="select m from eventBundle:event m Where 1=1";

        if(!empty($titre))
        {
            $sql=$sql." and m.titre='".$titre."'";
        }


        var_dump($sql);
        $qb=$this->getEntityManager()->
        createQuery($sql);


        return $query=$qb->getResult();



    }
}
