<?php

namespace JardinBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindDomaine()
    {
        $qb = $this->getEntityManager()
            ->createQuery
            ("SELECT  f.nom, f.prenom, f.age, f.photo, c.email FROM JardinBundle:Enfant f JOIN JardinBundle:User c WHERE
                    f.idUtilisateur=c.id");
        return $query = $qb->getResult();
    }
}
