jardin_reclamation:
    resource: "@JardinBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation

jardin_homepage:
    path:     /hello
    defaults: { _controller: JardinBundle:Default:index }
jardin_rec:
    path:     /admin/liste
    defaults: { _controller: JardinBundle:Reclamation:reclamation }
enfant_liste:
    path:     /admin/listenfant
    defaults: { _controller: JardinBundle:Enfant:enfant }
Stat:
    path:     /stat
    defaults: { _controller: JardinBundle:Reclamation:Stat }