reclamation_index:
    path:     /
    defaults: { _controller: "JardinBundle:Reclamation:index" }
    methods:  GET

reclamation_show:
    path:     /show
    defaults: { _controller: "JardinBundle:Reclamation:show" }
    methods:  GET

reclamation_new:
    path:     /new
    defaults: { _controller: "JardinBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{idReclamation}/edit
    defaults: { _controller: "JardinBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{idReclamation}/delete
    defaults: { _controller: "JardinBundle:Reclamation:delete" }
    methods:  DELETE
