jardin_enfant:
    resource: "@JardinBundle/Controller/EnfantController.php"
    type:     annotation

mobile:
    resource: "@MobileBundle/Resources/config/routing.yml"
    prefix:   /Mobile

jardin_cat_reclamation:
    resource: "@JardinBundle/Controller/CatReclamationController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

jardin:
    resource: "@JardinBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"